CONFIG_EVENTS=y
CONFIG_I3C=y
CONFIG_I3C_USE_IBI=y
CONFIG_I3C_CONTROLLER_ROLE_ONLY=y

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=4
CONFIG_LOG_OVERRIDE_LEVEL=4
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_BUFFER_SIZE=4096
#CONFIG_DEBUG_OPTIMIZATIONS=y


CONFIG_I3C_TEST_CASE=0
CONFIG_I3C_TEST_CRC_CHECK=y
