CONFIG_I2C=y
CONFIG_I2C_MCHP_MEC5_NL=y
CONFIG_I2C_MCHP_MEC5_MUX=y
CONFIG_I2C_TARGET=y
CONFIG_I2C_TARGET_BUFFER_MODE=y
CONFIG_I2C_CALLBACK=y
CONFIG_DMA=y
CONFIG_DMA_MCHP_XEC=y
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_I2C_LOG_LEVEL_INF=y
