CONFIG_LSM6DSV16X=n
CONFIG_LSM6DSVXXX=n
CONFIG_LPS2XDF=n
CONFIG_ICM45686=n

CONFIG_EVENTS=y
CONFIG_I3C=y
CONFIG_I3C_USE_IBI=y
CONFIG_I3C_TARGET_BUFFER_MODE=y

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=4
CONFIG_LOG_OVERRIDE_LEVEL=4
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_BUFFER_SIZE=4096
CONFIG_I3C_DW_LOG_LEVEL=4
#CONFIG_DEBUG_OPTIMIZATIONS=y

CONFIG_I3C_TEST_CASE=0
CONFIG_I3C_TEST_CRC_CHECK=y
CONFIG_I3C_TARGET_ECHO_MODE=y