/*
 * Copyright (c) 2025 Microchip Technology Inc.
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_ESPI_MCHP_XEC_ESPI_NG_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_ESPI_MCHP_XEC_ESPI_NG_H_

#define MCHP_XEC_ESPI_MAP_IO 0
#define MCHP_XEC_ESPI_MAP_MEM 1

#define MCHP_XEC_ESPI_VW_CT 0
#define MCHP_XEC_ESPI_VW_TC 1

#define MCHP_XEC_ESPI_CTVW00 0
#define MCHP_XEC_ESPI_CTVW01 1
#define MCHP_XEC_ESPI_CTVW02 2
#define MCHP_XEC_ESPI_CTVW03 3
#define MCHP_XEC_ESPI_CTVW04 4
#define MCHP_XEC_ESPI_CTVW05 5
#define MCHP_XEC_ESPI_CTVW06 6
#define MCHP_XEC_ESPI_CTVW07 7
#define MCHP_XEC_ESPI_CTVW08 8
#define MCHP_XEC_ESPI_CTVW09 9
#define MCHP_XEC_ESPI_CTVW10 10
#define MCHP_XEC_ESPI_TCVW00 11
#define MCHP_XEC_ESPI_TCVW01 12
#define MCHP_XEC_ESPI_TCVW02 13
#define MCHP_XEC_ESPI_TCVW03 14
#define MCHP_XEC_ESPI_TCVW04 15
#define MCHP_XEC_ESPI_TCVW05 16
#define MCHP_XEC_ESPI_TCVW06 17
#define MCHP_XEC_ESPI_TCVW07 18
#define MCHP_XEC_ESPI_TCVW08 19
#define MCHP_XEC_ESPI_TCVW09 20
#define MCHP_XEC_ESPI_TCVW10 21

#define MCHP_XEC_ESPI_FLAG_VW_CT 0
#define MCHP_XEC_ESPI_FLAG_VW_TC 0x1
#define MCHP_XEC_ESPI_FLAG_RST_VAL 0x2
#define MCHP_XEC_ESPI_FLAG_CURR_VAL 0x4

#define MCHP_XEC_ESPI_VW_RST_ESPI 0
#define MCHP_XEC_ESPI_VW_RST_SYS  0x1
#define MCHP_XEC_ESPI_VW_RST_SIO  0x2
#define MCHP_XEC_ESPI_VW_RST_PLTRST 0x3

#define MCHP_XEC_ESPI_CTVW_IRQSEL_NONE 0
#define MCHP_XEC_ESPI_CTVW_IRQSEL_LL   1
#define MCHP_XEC_ESPI_CTVW_IRQSEL_LH   2
#define MCHP_XEC_ESPI_CTVW_IRQSEL_RE   3
#define MCHP_XEC_ESPI_CTVW_IRQSEL_FE   4
#define MCHP_XEC_ESPI_CTVW_IRQSEL_BE   5

#define XEC_ESPI_VW_ISEL_NONE 0
#define XEC_ESPI_VW_ISEL_LL   1
#define XEC_ESPI_VW_ISEL_LH   2
#define XEC_ESPI_VW_ISEL_RE   3
#define XEC_ESPI_VW_ISEL_FE   4
#define XEC_ESPI_VW_ISEL_BE   5

#define MCHP_XEC_ESPI_VW_CFG_HI 0x1
#define MCHP_XEC_ESPI_VW_CFG_RST_SRC 0x2
#define MCHP_XEC_ESPI_VW_CFG_SRC0_RST_VAL 0x10
#define MCHP_XEC_ESPI_VW_CFG_SRC1_RST_VAL 0x20
#define MCHP_XEC_ESPI_VW_CFG_SRC2_RST_VAL 0x40
#define MCHP_XEC_ESPI_VW_CFG_SRC3_RST_VAL 0x80
#define MCHP_XEC_ESPI_VW_CFG_SRC0_VAL 0x100
#define MCHP_XEC_ESPI_VW_CFG_SRC1_VAL 0x200
#define MCHP_XEC_ESPI_VW_CFG_SRC2_VAL 0x400
#define MCHP_XEC_ESPI_VW_CFG_SRC3_VAL 0x800
#define MCHP_XEC_ESPI_VW_CFG_SRC0_IRQ 0x1000
#define MCHP_XEC_ESPI_VW_CFG_SRC1_IRQ 0x2000
#define MCHP_XEC_ESPI_VW_CFG_SRC2_IRQ 0x4000
#define MCHP_XEC_ESPI_VW_CFG_SRC3_IRQ 0x8000

#define MCHP_ESPI_VW_CFG_SRC_RST_VAL_ALL 0xf0
#define MCHP_ESPI_VW_CFG_SRC_VAL_ALL 0xf00
#define MCHP_ESPI_VW_CFG_SRC_IRQ_ALL 0xf000
#define MCHP_ESPI_VW_CFG_ALL_PROP 0xffff

#define MCHP_ESPI_PC_SIRQ_IDX_MBOX_EC_WR  0
#define MCHP_ESPI_PC_SIRQ_IDX_MBOX_EC_WR2 1
#define MCHP_ESPI_PC_SIRQ_IDX_KBC_KIRQ    2
#define MCHP_ESPI_PC_SIRQ_IDX_KBC_MIRQ    3
#define MCHP_ESPI_PC_SIRQ_IDX_AEC0_OBF    4
#define MCHP_ESPI_PC_SIRQ_IDX_AEC1_OBF    5
#define MCHP_ESPI_PC_SIRQ_IDX_AEC2_OBF    6
#define MCHP_ESPI_PC_SIRQ_IDX_AEC3_OBF    7
#define MCHP_ESPI_PC_SIRQ_IDX_AEC4_OBF    8
#define MCHP_ESPI_PC_SIRQ_IDX_UART0       9
#define MCHP_ESPI_PC_SIRQ_IDX_UART1       10
#define MCHP_ESPI_PC_SIRQ_IDX_EMI0_MB     11
#define MCHP_ESPI_PC_SIRQ_IDX_EMI0_MB_SWI 12
#define MCHP_ESPI_PC_SIRQ_IDX_EMI1_MB     13
#define MCHP_ESPI_PC_SIRQ_IDX_EMI1_MB_SWI 14
#define MCHP_ESPI_PC_SIRQ_IDX_EMI2_MB     15
#define MCHP_ESPI_PC_SIRQ_IDX_EMI2_MB_SWI 16
#define MCHP_ESPI_PC_SIRQ_IDX_RTC0        17
#define MCHP_ESPI_PC_SIRQ_IDX_EC_IRQ      18
#define MCHP_ESPI_PC_SIRQ_IDX_UART2       19
#define MCHP_ESPI_PC_SIRQ_IDX_UART3       20

/* The following defines must match values from the
 * enumerated type enum espi_vwire_signal
 */
#define XEC_ESPI_VW_SLP_S3           0
#define XEC_ESPI_VW_SLP_S4           1
#define XEC_ESPI_VW_SLP_S5           2
#define XEC_ESPI_VW_OOB_RST_WARN     3
#define XEC_ESPI_VW_PLTRST           4
#define XEC_ESPI_VW_SUS_STAT         5
#define XEC_ESPI_VW_NMIOUT           6
#define XEC_ESPI_VW_SMIOUT           7
#define XEC_ESPI_VW_HOST_RST_WARN    8
#define XEC_ESPI_VW_SLP_A            9
#define XEC_ESPI_VW_SUS_PWRDN_ACK    10
#define XEC_ESPI_VW_SUS_WARN         11
#define XEC_ESPI_VW_SLP_WLAN         12
#define XEC_ESPI_VW_SLP_LAN          13
#define XEC_ESPI_VW_HOST_C10         14
#define XEC_ESPI_VW_DNX_WARN         15

#define XEC_ESPI_VW_PME              16
#define XEC_ESPI_VW_WAKE             17
#define XEC_ESPI_VW_OOB_RST_ACK      18
#define XEC_ESPI_VW_TARGET_BOOT_STS  19
#define XEC_ESPI_VW_ERR_NON_FATAL    20
#define XEC_ESPI_VW_ERR_FATAL        21
#define XEC_ESPI_VW_TARGET_BOOT_DONE 22
#define XEC_ESPI_VW_HOST_RST_ACK     23
#define XEC_ESPI_VW_RST_CPU_INIT     24
#define XEC_ESPI_VW_SMI              25
#define XEC_ESPI_VW_SCI              26
#define XEC_ESPI_VW_DNX_ACK          27
#define XEC_ESPI_VW_SUS_ACK          28


#define XEC_ESPI_VW_TARGET_GPIO_0    29
#define XEC_ESPI_VW_TARGET_GPIO_1    30
#define XEC_ESPI_VW_TARGET_GPIO_2    31
#define XEC_ESPI_VW_TARGET_GPIO_3    32
#define XEC_ESPI_VW_TARGET_GPIO_4    33
#define XEC_ESPI_VW_TARGET_GPIO_5    34
#define XEC_ESPI_VW_TARGET_GPIO_6    35
#define XEC_ESPI_VW_TARGET_GPIO_7    36
#define XEC_ESPI_VW_TARGET_GPIO_8    37
#define XEC_ESPI_VW_TARGET_GPIO_9    38
#define XEC_ESPI_VW_TARGET_GPIO_10   39
#define XEC_ESPI_VW_TARGET_GPIO_11   40

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_ESPI_MCHP_XEC_ESPI_NG_H_ */
