# Enable config log
CONFIG_STDOUT_CONSOLE=y
CONFIG_LOG=y
# default CONFIG_LOG_BUFFER_SIZE=1024
# increase since we are logging I2C driver target mode callbacks
CONFIG_LOG_BUFFER_SIZE=6144

CONFIG_DMA=y
CONFIG_I2C=y
#CONFIG_I2C_XEC_PORT_SWITCHING=y
CONFIG_I2C_TARGET=y
# this adds two more APIs.
# original byte mode target APIs are still present.
CONFIG_I2C_TARGET_BUFFER_MODE=y
# CONFIG_I2C_LOG_LEVEL_DBG=y
# CONFIG_I2C_XEC_NL_TRACE_DEBUG=y

CONFIG_PM=n
# CONFIG_PM_DEVICE=y

# debug macro expansion in C source files
# does not delete build/../source_c_file_name.c.i
# CONFIG_COMPILER_SAVE_TEMPS=y
# CONFIG_DEBUG=y
