/*
 * Copyright (c) 2026 Microchip Technology Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file mchp_xec_espi.h
 * @brief Microchip eSPI Driver Header
 *
 * @details
 * This header provides conditional inclusion of Microchip eSPI controller
 * extension to types from espi.h
 */

#ifndef INCLUDE_ZEPHYR_DRIVERS_ESPI_MCHP_XEC_ESPI_H_
#define INCLUDE_ZEPHYR_DRIVERS_ESPI_MCHP_XEC_ESPI_H_

#include <zephyr/device.h>
#include <zephyr/drivers/espi.h>
#include <zephyr/sys/slist.h>

#if defined(CONFIG_ESPI_PERIPHERAL_XEC_MAILBOX) || defined(CONFIG_ESPI_XEC_V3_PC_MBOX)

#define MCHP_XEC_MAX_MAILBOX_INDEX 32

/**
 * Vendor-specific peripheral identifier reported in @ref espi_event::evt_details
 * for events generated by the Microchip XEC mailbox peripheral. Placed above
 * the highest value in @ref espi_virtual_peripheral so it does not collide with
 * future generic additions.
 */
#define MCHP_XEC_ESPI_PERIPHERAL_MAILBOX 0x100U

enum mchp_xec_espi_pc_mbox_cmd_id {
	MCHP_XEC_ESPI_PC_MBOX_CMD_ID_HOST_TO_EC = 0,
	MCHP_XEC_ESPI_PC_MBOX_CMD_ID_EC_TO_HOST,
	MCHP_XEC_ESPI_PC_MBOX_CMD_ID_SMI_SRC,
	MCHP_XEC_ESPI_PC_MBOX_CMD_ID_SMI_MASK,
	MCHP_XEC_ESPI_PC_MBOX_CMD_ID_MAX,
};

enum mchp_xec_espi_pc_mbox_isrc {
	MCHP_XEC_ESPI_PC_MBOX_ISRC_EC = 0,
	MCHP_XEC_ESPI_PC_MBOX_ISRC_SIRQ,
	MCHP_XEC_ESPI_PC_MBOX_ISRC_SIRQ_SMI,
	MCHP_XEC_ESPI_PC_MBOX_ISRC_MAX,
};

/** @brief Read peripheral channel mailbox data
 *
 * @param dev Pointer to the device structure for the driver instance
 * @param mbox_idx
 * @param num_mboxes
 * @param dest
 *
 * @retval 0 success
 * @retval -EINVAL if dev is NULL or mbox_idx > 32 or dest is NULL
 */
int mchp_xec_espi_pc_mailbox_get(const struct device *dev, uint8_t mbox_idx, uint8_t num_mboxes,
				 uint8_t *dest);

/** @brief Write peripheral channel mailbox data
 *
 * @param dev Pointer to the device structure for the driver instance
 * @param mbox_idx
 * @param num_mboxes
 * @param src
 *
 * @retval 0 success
 * @retval -EINVAL if dev is NULL or mbox_idx > 32 or dest is NULL
 */
int mchp_xec_espi_pc_mailbox_set(const struct device *dev, uint8_t mbox_idx, uint8_t num_mboxes,
				 const uint8_t *src);

/** @brief Read all 32-byte of the peripheral channel mailbox data
 *
 * @param dev Pointer to the device structure for the driver instance
 * @param dest pointer to >= 32-bit aligned buffer at least 32 bytes in size
 *
 * @retval 0 success
 * @retval -EINVAL if dev or dest is NULL
 */
int mchp_xec_espi_pc_mailbox_get_all(const struct device *dev, uint32_t *dest);

/** @brief Write all 32 bytes of the peripheral channel mailbox data
 *
 * @param dev Pointer to the device structure for the driver instance
 * @param src pointer to 32-bit aligned constant buffer of 32 bytes.
 *
 * @retval 0 success
 * @retval -EINVAL if dev or src are NULL
 */
int mchp_xec_espi_pc_mailbox_set_all(const struct device *dev, const uint32_t *src);

/** @brief Write command to specified mailbox box command register
 *
 * @param dev Pointer to the device structure for the driver instance
 * @param cmd_id enum mchp_xec_espi_pc_mbox_cmd_id specifies the mailbox command register
 *               to write.
 * @param cmd
 *
 * @retval 0 success
 * @retval -EINVAL if dev is NULL or cmd_id is invalid
 */
int mchp_xec_espi_pc_mailbox_cmd(const struct device *dev, enum mchp_xec_espi_pc_mbox_cmd_id cmd_id,
				 uint8_t cmd);

/** @brief Write command to specified mailbox box command register
 *
 * @param dev Pointer to the device structure for the driver instance
 * @param id enum mchp_xec_espi_pc_mbox_isrc specifying the interrupt (internal EC or serial IRQ)
 * @param enable a zero value is disable else enable
 *
 * @retval 0 success
 * @retval -EINVAL if dev is NULL or id is invalid
 */
int mchp_xec_espi_pc_mailbox_ictrl(const struct device *dev, enum mchp_xec_espi_pc_mbox_isrc id,
				   uint8_t enable);

#endif /* CONFIG_ESPI_PERIPHERAL_XEC_MAILBOX || CONFIG_ESPI_XEC_V3_PC_MBOX */

#ifdef CONFIG_ESPI_XEC_V3

/**
 * @brief Events the XEC eSPI V3 controller reports to peripheral channel drivers.
 *
 * MEC hardware holds the I/O BAR, Memory BAR and Serial-IRQ registers of every
 * peripheral channel logical device in reset while eSPI Reset or PLTRST is
 * asserted, and clears them when the peripheral channel is disabled. Only the
 * controller driver observes those transitions, so peripheral channel drivers
 * register for them and use the notification as the point at which their
 * Host facing decoders are known to be valid.
 *
 * The controller guarantees the following ordering:
 *
 * - Becoming usable (@ref MCHP_XEC_ESPI_PC_EVT_ESPI_RESET_DEASSERT,
 *   @ref MCHP_XEC_ESPI_PC_EVT_PLTRST_DEASSERT,
 *   @ref MCHP_XEC_ESPI_PC_EVT_CHAN_ENABLED): every enabled logical device's
 *   BARs and Serial-IRQ registers are re-programmed from device tree *before*
 *   the notification is delivered.
 * - Going away (@ref MCHP_XEC_ESPI_PC_EVT_ESPI_RESET_ASSERT,
 *   @ref MCHP_XEC_ESPI_PC_EVT_PLTRST_ASSERT,
 *   @ref MCHP_XEC_ESPI_PC_EVT_CHAN_DISABLED): the notification is delivered
 *   *before* the hardware holds the registers in reset, giving the peripheral
 *   driver a chance to quiesce pending Host operations.
 *
 * Handlers run in the controller's interrupt context and must not block.
 */
enum mchp_xec_espi_pc_event {
	MCHP_XEC_ESPI_PC_EVT_ESPI_RESET_ASSERT = 0,
	MCHP_XEC_ESPI_PC_EVT_ESPI_RESET_DEASSERT,
	MCHP_XEC_ESPI_PC_EVT_CHAN_DISABLED,
	MCHP_XEC_ESPI_PC_EVT_CHAN_ENABLED,
	MCHP_XEC_ESPI_PC_EVT_PLTRST_ASSERT,
	MCHP_XEC_ESPI_PC_EVT_PLTRST_DEASSERT,
	MCHP_XEC_ESPI_PC_EVT_MAX,
};

/**
 * @brief Peripheral channel event handler.
 *
 * @param espi_dev eSPI controller device delivering the event
 * @param pc_dev peripheral channel device the registration belongs to
 * @param evt event being delivered
 */
typedef void (*mchp_xec_espi_pc_handler_t)(const struct device *espi_dev,
					   const struct device *pc_dev,
					   enum mchp_xec_espi_pc_event evt);

/**
 * @brief Peripheral channel LPC request handler.
 *
 * Implements one contiguous range of @ref lpc_peripheral_opcode on behalf of
 * the controller's espi_read_lpc_request() / espi_write_lpc_request() shims.
 *
 * @param pc_dev peripheral channel device the registration belongs to
 * @param op opcode, guaranteed to be within the registered range
 * @param data in/out data for the opcode
 * @param write true for a write request, false for a read request
 *
 * @retval 0 success
 * @retval -ENOTSUP opcode is not implemented by this device
 * @retval -EINVAL invalid arguments
 */
typedef int (*mchp_xec_espi_pc_lpc_req_t)(const struct device *pc_dev,
					  enum lpc_peripheral_opcode op, uint32_t *data,
					  bool write);

/**
 * @brief Peripheral channel registration.
 *
 * Owned by the peripheral channel driver and must stay allocated for as long
 * as the registration is active. Fill in @ref pc_dev and @ref evt_mask plus
 * @ref handler, and optionally the LPC request fields, before calling
 * mchp_xec_espi_pc_register().
 */
struct mchp_xec_espi_pc_cb {
	/** Internal list node, do not touch. */
	sys_snode_t node;
	/** Peripheral channel device this registration belongs to. */
	const struct device *pc_dev;
	/** Event handler. May be NULL if only the LPC shim is required. */
	mchp_xec_espi_pc_handler_t handler;
	/** Bit mask of BIT(enum mchp_xec_espi_pc_event) values of interest. */
	uint32_t evt_mask;
	/** LPC request handler. NULL means this device serves no opcodes. */
	mchp_xec_espi_pc_lpc_req_t lpc_request;
	/** First @ref lpc_peripheral_opcode served, inclusive. */
	uint16_t lpc_op_start;
	/** Last @ref lpc_peripheral_opcode served, inclusive. */
	uint16_t lpc_op_end;
};

/** @brief Register a peripheral channel device with the eSPI controller
 *
 * @param espi_dev eSPI controller device, normally DEVICE_DT_GET(DT_INST_PARENT(n))
 * @param cb registration filled in by the caller and owned by the caller
 *
 * @retval 0 success
 * @retval -EINVAL espi_dev or cb is NULL, or cb->pc_dev is NULL
 * @retval -EALREADY cb is already registered with this controller
 */
int mchp_xec_espi_pc_register(const struct device *espi_dev, struct mchp_xec_espi_pc_cb *cb);

/** @brief Remove a peripheral channel registration
 *
 * @param espi_dev eSPI controller device the registration was added to
 * @param cb registration previously passed to mchp_xec_espi_pc_register()
 *
 * @retval 0 success
 * @retval -EINVAL espi_dev or cb is NULL
 * @retval -ENOENT cb is not registered with this controller
 */
int mchp_xec_espi_pc_unregister(const struct device *espi_dev, struct mchp_xec_espi_pc_cb *cb);

#endif /* CONFIG_ESPI_XEC_V3 */

#ifdef CONFIG_ESPI_XEC_V3_PC_ACPI_PM1

/**
 * Vendor-specific peripheral identifier reported in @ref espi_event::evt_details
 * for events generated by the ACPI PM1 block. The generic
 * @ref espi_virtual_peripheral list has no ACPI fixed hardware entry, so this
 * follows @ref MCHP_XEC_ESPI_PERIPHERAL_MAILBOX above the highest generic value.
 */
#define MCHP_XEC_ESPI_PERIPHERAL_ACPI_PM1 0x101U

/** @brief EC-side ACPI PM1 registers
 *
 * The Host sees the PM1 status, enable and control registers in its I/O space.
 * The EC sees the same state through the aliases named here.
 */
enum mchp_xec_espi_pc_acpi_pm1_reg {
	/** PM1 status 1. Reserved by the ACPI specification, always zero. */
	MCHP_XEC_ESPI_PC_ACPI_PM1_REG_STS1 = 0,
	/** PM1 status 2. Power button, sleep button, RTC and wake status. */
	MCHP_XEC_ESPI_PC_ACPI_PM1_REG_STS2,
	/** PM1 enable 1. Reserved by the ACPI specification, always zero. */
	MCHP_XEC_ESPI_PC_ACPI_PM1_REG_EN1,
	/** PM1 enable 2. Power button, sleep button and RTC enables. */
	MCHP_XEC_ESPI_PC_ACPI_PM1_REG_EN2,
	/** PM1 control 1. Reserved by the ACPI specification, always zero. */
	MCHP_XEC_ESPI_PC_ACPI_PM1_REG_CTRL1,
	/** PM1 control 2. Sleep type, sleep enable and power button override. */
	MCHP_XEC_ESPI_PC_ACPI_PM1_REG_CTRL2,
	/** PM1 control 2 byte 1. Reserved by the ACPI specification. */
	MCHP_XEC_ESPI_PC_ACPI_PM1_REG_CTRL21,
	/** PM1 control 2 byte 2. Reserved by the ACPI specification. */
	MCHP_XEC_ESPI_PC_ACPI_PM1_REG_CTRL22,
	/** EC power management status. Bit 0 is the SCI request. */
	MCHP_XEC_ESPI_PC_ACPI_PM1_REG_PM_STS,
	MCHP_XEC_ESPI_PC_ACPI_PM1_REG_MAX,
};

/** @brief Event data reported for an ACPI PM1 event
 *
 * Placed in @ref espi_event::evt_data when @ref espi_event::evt_details is
 * @ref MCHP_XEC_ESPI_PERIPHERAL_ACPI_PM1.
 */
struct mchp_xec_espi_pc_acpi_pm1_evt {
	/** enum mchp_xec_espi_pc_acpi_pm1_reg the Host wrote */
	uint32_t reg: 8;
	/** Value the register holds after the Host write */
	uint32_t data: 8;
	/** Reserved for future use */
	uint32_t reserved: 16;
};

/** @brief Read an EC-side ACPI PM1 register
 *
 * @param dev ACPI PM1 peripheral channel device
 * @param reg register to read
 * @param val destination for the register value
 *
 * @retval 0 success
 * @retval -EINVAL dev or val is NULL, or reg is out of range
 */
int mchp_xec_espi_pc_acpi_pm1_get(const struct device *dev,
				  enum mchp_xec_espi_pc_acpi_pm1_reg reg, uint8_t *val);

/** @brief Write an EC-side ACPI PM1 register
 *
 * Bits the ACPI specification reserves are read-only in hardware and ignore the
 * value written.
 *
 * @param dev ACPI PM1 peripheral channel device
 * @param reg register to write
 * @param val value to write
 *
 * @retval 0 success
 * @retval -EINVAL dev is NULL or reg is out of range
 */
int mchp_xec_espi_pc_acpi_pm1_set(const struct device *dev,
				  enum mchp_xec_espi_pc_acpi_pm1_reg reg, uint8_t val);

#endif /* CONFIG_ESPI_XEC_V3_PC_ACPI_PM1 */


#endif /* INCLUDE_ZEPHYR_DRIVERS_ESPI_MCHP_XEC_ESPI_H_ */
