/*
 * Copyright (c) 2026 Microchip Technology Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file mchp_xec_espi.h
 * @brief Microchip eSPI Driver Header
 *
 * @details
 * This header provides conditional inclusion of Microchip eSPI controller
 * extension to types from espi.h
 */

#ifndef INCLUDE_ZEPHYR_DRIVERS_ESPI_MCHP_XEC_ESPI_H_
#define INCLUDE_ZEPHYR_DRIVERS_ESPI_MCHP_XEC_ESPI_H_

#include <zephyr/device.h>
#include <zephyr/drivers/espi.h>
#include <zephyr/sys/slist.h>

#if defined(CONFIG_ESPI_PERIPHERAL_XEC_MAILBOX) || defined(CONFIG_ESPI_XEC_V3_PC_MBOX)

#define MCHP_XEC_MAX_MAILBOX_INDEX 32

/**
 * Vendor-specific peripheral identifier reported in @ref espi_event::evt_details
 * for events generated by the Microchip XEC mailbox peripheral. Placed above
 * the highest value in @ref espi_virtual_peripheral so it does not collide with
 * future generic additions.
 */
#define MCHP_XEC_ESPI_PERIPHERAL_MAILBOX 0x100U

enum mchp_xec_espi_pc_mbox_cmd_id {
	MCHP_XEC_ESPI_PC_MBOX_CMD_ID_HOST_TO_EC = 0,
	MCHP_XEC_ESPI_PC_MBOX_CMD_ID_EC_TO_HOST,
	MCHP_XEC_ESPI_PC_MBOX_CMD_ID_SMI_SRC,
	MCHP_XEC_ESPI_PC_MBOX_CMD_ID_SMI_MASK,
	MCHP_XEC_ESPI_PC_MBOX_CMD_ID_MAX,
};

enum mchp_xec_espi_pc_mbox_isrc {
	MCHP_XEC_ESPI_PC_MBOX_ISRC_EC = 0,
	MCHP_XEC_ESPI_PC_MBOX_ISRC_SIRQ,
	MCHP_XEC_ESPI_PC_MBOX_ISRC_SIRQ_SMI,
	MCHP_XEC_ESPI_PC_MBOX_ISRC_MAX,
};

/** @brief Read peripheral channel mailbox data
 *
 * @param dev Pointer to the device structure for the driver instance
 * @param mbox_idx index of the first mailbox data byte to read
 * @param num_mboxes number of mailbox data bytes to read, starting at mbox_idx.
 *                   The V2 driver instead treats this as an exclusive end index
 *                   and reads nothing when it is not above mbox_idx.
 * @param dest buffer of at least num_mboxes bytes
 *
 * @retval 0 success
 * @retval -EINVAL if dev is NULL or dest is NULL or the run leaves the 32 byte
 *                 block
 */
int mchp_xec_espi_pc_mailbox_get(const struct device *dev, uint8_t mbox_idx, uint8_t num_mboxes,
				 uint8_t *dest);

/** @brief Write peripheral channel mailbox data
 *
 * @param dev Pointer to the device structure for the driver instance
 * @param mbox_idx index of the first mailbox data byte to write
 * @param num_mboxes number of mailbox data bytes to write, starting at
 *                   mbox_idx. The V2 driver instead treats this as an exclusive
 *                   end index and writes nothing when it is not above mbox_idx.
 * @param src buffer of at least num_mboxes bytes
 *
 * @retval 0 success
 * @retval -EINVAL if dev is NULL or src is NULL or the run leaves the 32 byte
 *                 block
 */
int mchp_xec_espi_pc_mailbox_set(const struct device *dev, uint8_t mbox_idx, uint8_t num_mboxes,
				 const uint8_t *src);

/** @brief Read all 32-byte of the peripheral channel mailbox data
 *
 * @param dev Pointer to the device structure for the driver instance
 * @param dest pointer to >= 32-bit aligned buffer at least 32 bytes in size
 *
 * @retval 0 success
 * @retval -EINVAL if dev or dest is NULL
 */
int mchp_xec_espi_pc_mailbox_get_all(const struct device *dev, uint32_t *dest);

/** @brief Write all 32 bytes of the peripheral channel mailbox data
 *
 * @param dev Pointer to the device structure for the driver instance
 * @param src pointer to 32-bit aligned constant buffer of 32 bytes.
 *
 * @retval 0 success
 * @retval -EINVAL if dev or src are NULL
 */
int mchp_xec_espi_pc_mailbox_set_all(const struct device *dev, const uint32_t *src);

/** @brief Write command to specified mailbox box command register
 *
 * @param dev Pointer to the device structure for the driver instance
 * @param cmd_id enum mchp_xec_espi_pc_mbox_cmd_id specifies the mailbox command register
 *               to write.
 * @param cmd
 *
 * @retval 0 success
 * @retval -EINVAL if dev is NULL or cmd_id is invalid
 */
int mchp_xec_espi_pc_mailbox_cmd(const struct device *dev, enum mchp_xec_espi_pc_mbox_cmd_id cmd_id,
				 uint8_t cmd);

/** @brief Write command to specified mailbox box command register
 *
 * @param dev Pointer to the device structure for the driver instance
 * @param id enum mchp_xec_espi_pc_mbox_isrc specifying the interrupt (internal EC or serial IRQ)
 * @param enable a zero value is disable else enable
 *
 * @retval 0 success
 * @retval -EINVAL if dev is NULL or id is invalid
 */
int mchp_xec_espi_pc_mailbox_ictrl(const struct device *dev, enum mchp_xec_espi_pc_mbox_isrc id,
				   uint8_t enable);

#endif /* CONFIG_ESPI_PERIPHERAL_XEC_MAILBOX || CONFIG_ESPI_XEC_V3_PC_MBOX */

#ifdef CONFIG_ESPI_XEC_V3

/**
 * @brief Events the XEC eSPI V3 controller reports to peripheral channel drivers.
 *
 * MEC hardware holds the I/O BAR, Memory BAR and Serial-IRQ registers of every
 * peripheral channel logical device in reset while eSPI Reset or PLTRST is
 * asserted, and clears them when the peripheral channel is disabled. Only the
 * controller driver observes those transitions, so peripheral channel drivers
 * register for them and use the notification as the point at which their
 * Host facing decoders are known to be valid.
 *
 * The controller guarantees the following ordering:
 *
 * - Becoming usable (@ref MCHP_XEC_ESPI_PC_EVT_ESPI_RESET_DEASSERT,
 *   @ref MCHP_XEC_ESPI_PC_EVT_PLTRST_DEASSERT,
 *   @ref MCHP_XEC_ESPI_PC_EVT_CHAN_ENABLED): every enabled logical device's
 *   BARs and Serial-IRQ registers are re-programmed from device tree *before*
 *   the notification is delivered.
 * - Going away (@ref MCHP_XEC_ESPI_PC_EVT_ESPI_RESET_ASSERT,
 *   @ref MCHP_XEC_ESPI_PC_EVT_PLTRST_ASSERT,
 *   @ref MCHP_XEC_ESPI_PC_EVT_CHAN_DISABLED): the notification is delivered
 *   *before* the hardware holds the registers in reset, giving the peripheral
 *   driver a chance to quiesce pending Host operations.
 *
 * Handlers run in the controller's interrupt context and must not block.
 */
enum mchp_xec_espi_pc_event {
	MCHP_XEC_ESPI_PC_EVT_ESPI_RESET_ASSERT = 0,
	MCHP_XEC_ESPI_PC_EVT_ESPI_RESET_DEASSERT,
	MCHP_XEC_ESPI_PC_EVT_CHAN_DISABLED,
	MCHP_XEC_ESPI_PC_EVT_CHAN_ENABLED,
	MCHP_XEC_ESPI_PC_EVT_PLTRST_ASSERT,
	MCHP_XEC_ESPI_PC_EVT_PLTRST_DEASSERT,
	MCHP_XEC_ESPI_PC_EVT_MAX,
};

/**
 * @brief Peripheral channel event handler.
 *
 * @param espi_dev eSPI controller device delivering the event
 * @param pc_dev peripheral channel device the registration belongs to
 * @param evt event being delivered
 */
typedef void (*mchp_xec_espi_pc_handler_t)(const struct device *espi_dev,
					   const struct device *pc_dev,
					   enum mchp_xec_espi_pc_event evt);

/**
 * @brief Peripheral channel LPC request handler.
 *
 * Implements one contiguous range of @ref lpc_peripheral_opcode on behalf of
 * the controller's espi_read_lpc_request() / espi_write_lpc_request() shims.
 *
 * @param pc_dev peripheral channel device the registration belongs to
 * @param op opcode, guaranteed to be within the registered range
 * @param data in/out data for the opcode
 * @param write true for a write request, false for a read request
 *
 * @retval 0 success
 * @retval -ENOTSUP opcode is not implemented by this device
 * @retval -EINVAL invalid arguments
 */
typedef int (*mchp_xec_espi_pc_lpc_req_t)(const struct device *pc_dev,
					  enum lpc_peripheral_opcode op, uint32_t *data,
					  bool write);

/**
 * @name Peripheral channel interrupt sources
 *
 * Each logical device names its own interrupt sources, because a bit that meant
 * the same thing on every device could only ever name a device class, and the
 * sources within one class are not interchangeable: 8042 input buffer full is
 * an edge source that wants to stay armed, while output buffer empty is a level
 * source that must stay masked until there is a byte for the Host. A source bit
 * is therefore only meaningful together with the device it is passed with, and
 * mchp_xec_espi_pc_intr_get() reports which bits a given device implements.
 *
 * @{
 */

/** 8042 KBC: the Host wrote the command or data register. Edge. */
#define MCHP_XEC_ESPI_PC_KBC_SRC_IBF BIT(0)
/**
 * 8042 KBC: the Host read the output buffer. Level, asserted for as long as the
 * buffer is empty, so the driver arms it only after writing a byte for the Host
 * and masks it again in the handler.
 */
#define MCHP_XEC_ESPI_PC_KBC_SRC_OBE BIT(1)

/** ACPI EC: the Host wrote the command or data register. Edge. */
#define MCHP_XEC_ESPI_PC_ACPI_EC_SRC_IBF BIT(0)
/** ACPI EC: the Host read the data register. Level, as @ref MCHP_XEC_ESPI_PC_KBC_SRC_OBE. */
#define MCHP_XEC_ESPI_PC_ACPI_EC_SRC_OBE BIT(1)

/** ACPI PM1: the Host wrote the PM1 control register. */
#define MCHP_XEC_ESPI_PC_ACPI_PM1_SRC_CTL BIT(0)
/** ACPI PM1: the Host wrote the PM1 enable register. */
#define MCHP_XEC_ESPI_PC_ACPI_PM1_SRC_EN  BIT(1)
/** ACPI PM1: the Host wrote the PM1 status register. */
#define MCHP_XEC_ESPI_PC_ACPI_PM1_SRC_STS BIT(2)

/** EMI: the Host wrote the Host-to-EC mailbox register. */
#define MCHP_XEC_ESPI_PC_EMI_SRC_H2EC BIT(0)

/**
 * Mailbox: the Host wrote the Host-to-EC register. This is the block's only EC
 * interrupt source; its two Serial-IRQ outputs are Host facing IRQ delivery
 * owned by the controller and stay with
 * mchp_xec_espi_pc_mailbox_ictrl().
 */
#define MCHP_XEC_ESPI_PC_MBOX_SRC_EC BIT(0)

/** Port 80 capture: the FIFO reached its threshold. */
#define MCHP_XEC_ESPI_PC_P80BD_SRC_THRESHOLD BIT(0)

/** Glue logic: the derived VCC_PWRGD2 power good signal changed. */
#define MCHP_XEC_ESPI_PC_GLUE_SRC_PWRGD BIT(0)
/** Glue logic: the derived S0ix connected standby state changed. */
#define MCHP_XEC_ESPI_PC_GLUE_SRC_S0IX  BIT(1)

/** @} */

/**
 * @brief Peripheral channel interrupt apply handler.
 *
 * Pushes @ref mchp_xec_espi_pc_cb::intr_src_en to the logical device's hardware.
 * The controller calls it after changing that word, and the peripheral driver
 * calls it itself once its event handler reports the Host facing hardware usable
 * again, because MEC hardware clears a block's enables along with its BARs. The
 * application therefore asks once, however many times the bus resets afterwards.
 *
 * A level source is left masked here even when its bit is set, because it would
 * assert for as long as the Host has nothing to do. The driver arms such a
 * source at the point it has data for the Host, and only if its bit is set.
 *
 * @param pc_dev peripheral channel device the registration belongs to
 */
typedef void (*mchp_xec_espi_pc_intr_apply_t)(const struct device *pc_dev);

/**
 * @brief Peripheral channel registration.
 *
 * Owned by the peripheral channel driver and must stay allocated for as long
 * as the registration is active. Fill in @ref pc_dev and @ref evt_mask plus
 * @ref handler, and optionally the LPC request fields, before calling
 * mchp_xec_espi_pc_register().
 */
struct mchp_xec_espi_pc_cb {
	/** Internal list node, do not touch. */
	sys_snode_t node;
	/** Peripheral channel device this registration belongs to. */
	const struct device *pc_dev;
	/** Event handler. May be NULL if only the LPC shim is required. */
	mchp_xec_espi_pc_handler_t handler;
	/** Bit mask of BIT(enum mchp_xec_espi_pc_event) values of interest. */
	uint32_t evt_mask;
	/** LPC request handler. NULL means this device serves no opcodes. */
	mchp_xec_espi_pc_lpc_req_t lpc_request;
	/** First @ref lpc_peripheral_opcode served, inclusive. */
	uint16_t lpc_op_start;
	/** Last @ref lpc_peripheral_opcode served, inclusive. */
	uint16_t lpc_op_end;
	/**
	 * Interrupt sources this device implements, as its own
	 * MCHP_XEC_ESPI_PC_*_SRC_* bits. Zero, the default, means the device has
	 * no Host facing interrupt sources of its own.
	 */
	uint32_t intr_src_supported;
	/**
	 * Interrupt sources currently asked for, a subset of
	 * @ref intr_src_supported. The peripheral driver seeds it before
	 * registering and reads it from @ref intr_apply; every change after that
	 * belongs to mchp_xec_espi_pc_intr_set(), so a driver must not write it
	 * once registered.
	 */
	uint32_t intr_src_en;
	/**
	 * Applies @ref intr_src_en to hardware. NULL means the device has no
	 * sources to apply and mchp_xec_espi_pc_intr_set() reports -ENOTSUP.
	 */
	mchp_xec_espi_pc_intr_apply_t intr_apply;
	/**
	 * Bit mask of @ref espi_interrupt_flags values this device answers to.
	 * espi_interrupt_config() sets @ref intr_src_en to all of
	 * @ref intr_src_supported when passed any of these bits and to none of
	 * them when passed none, which is the whole of the control a class based
	 * flag word can express. Zero, the default, keeps that API away from this
	 * device, which is the right answer where no generic flag describes its
	 * sources.
	 */
	uint32_t intr_flags;
};

/** @brief Register a peripheral channel device with the eSPI controller
 *
 * @param espi_dev eSPI controller device, normally DEVICE_DT_GET(DT_INST_PARENT(n))
 * @param cb registration filled in by the caller and owned by the caller
 *
 * @retval 0 success
 * @retval -EINVAL espi_dev or cb is NULL, or cb->pc_dev is NULL
 * @retval -EALREADY cb is already registered with this controller
 */
int mchp_xec_espi_pc_register(const struct device *espi_dev, struct mchp_xec_espi_pc_cb *cb);

/** @brief Remove a peripheral channel registration
 *
 * @param espi_dev eSPI controller device the registration was added to
 * @param cb registration previously passed to mchp_xec_espi_pc_register()
 *
 * @retval 0 success
 * @retval -EINVAL espi_dev or cb is NULL
 * @retval -ENOENT cb is not registered with this controller
 */
int mchp_xec_espi_pc_unregister(const struct device *espi_dev, struct mchp_xec_espi_pc_cb *cb);

/** @brief Enable or disable individual interrupt sources of one logical device
 *
 * Corrects, for Microchip XEC, what espi_interrupt_config() cannot express:
 *
 * - It is addressed to the peripheral device, so instances of one class, such as
 *   several ACPI EC blocks, are controlled separately.
 * - Its bits name interrupt sources rather than a device class, so sources that
 *   need opposite treatment, such as 8042 input buffer full and output buffer
 *   empty, are controlled separately.
 * - It takes a mask and a value rather than setting a whole word absolutely, so
 *   a caller changes one source without keeping a shadow copy of driver state.
 * - A source the device does not implement is rejected rather than dropped
 *   silently.
 *
 * The request is remembered and re-applied whenever the controller reports the
 * Host facing hardware usable again, because MEC hardware clears a peripheral
 * block's enables along with its BARs while eSPI Reset or PLTRST is asserted. An
 * application therefore calls this once and not again after every bus reset.
 *
 * Enabling a level source records the request but does not arm the hardware,
 * because such a source asserts for as long as the Host has nothing to do. The
 * driver arms it when it has data for the Host and masks it again once the Host
 * has taken it.
 *
 * @param pc_dev peripheral channel logical device, not the eSPI controller
 * @param src_mask sources to change, as that device's MCHP_XEC_ESPI_PC_*_SRC_*
 *                 bits. Sources outside the mask keep their current setting.
 * @param src_value new setting for the sources in @p src_mask, a 1 enabling and
 *                  a 0 disabling. Bits outside @p src_mask are ignored.
 *
 * @retval 0 success
 * @retval -EINVAL pc_dev is NULL, src_mask is zero, or src_mask names a source
 *                 the device does not implement
 * @retval -ENODEV pc_dev is not registered with an eSPI controller
 * @retval -ENOTSUP the device has no interrupt sources
 */
int mchp_xec_espi_pc_intr_set(const struct device *pc_dev, uint32_t src_mask, uint32_t src_value);

/** @brief Read back the interrupt sources of one logical device
 *
 * The companion espi_interrupt_config() never had. @p src_supported lets a
 * caller discover which sources a device implements rather than infer them from
 * a class name, and @p src_enabled reports what is currently asked for, so a
 * read-modify-write needs no shadow copy.
 *
 * @p src_enabled reflects the request, which is what survives a bus reset. It
 * can differ from the hardware at two documented moments: a level source that is
 * enabled but not armed because the driver has no data for the Host, and a
 * one-shot source a handler masked pending the application's next command.
 *
 * @param pc_dev peripheral channel logical device, not the eSPI controller
 * @param src_enabled destination for the sources currently enabled, or NULL
 * @param src_supported destination for the sources the device implements, or
 *                      NULL. Zero means the device has none.
 *
 * @retval 0 success
 * @retval -EINVAL pc_dev is NULL
 * @retval -ENODEV pc_dev is not registered with an eSPI controller
 */
int mchp_xec_espi_pc_intr_get(const struct device *pc_dev, uint32_t *src_enabled,
			      uint32_t *src_supported);

#endif /* CONFIG_ESPI_XEC_V3 */

#ifdef CONFIG_ESPI_XEC_V3_PC_ACPI_PM1

/**
 * Vendor-specific peripheral identifier reported in @ref espi_event::evt_details
 * for events generated by the ACPI PM1 block. The generic
 * @ref espi_virtual_peripheral list has no ACPI fixed hardware entry, so this
 * follows @ref MCHP_XEC_ESPI_PERIPHERAL_MAILBOX above the highest generic value.
 */
#define MCHP_XEC_ESPI_PERIPHERAL_ACPI_PM1 0x101U

/** @brief EC-side ACPI PM1 registers
 *
 * The Host sees the PM1 status, enable and control registers in its I/O space.
 * The EC sees the same state through the aliases named here.
 */
enum mchp_xec_espi_pc_acpi_pm1_reg {
	/** PM1 status 1. Reserved by the ACPI specification, always zero. */
	MCHP_XEC_ESPI_PC_ACPI_PM1_REG_STS1 = 0,
	/** PM1 status 2. Power button, sleep button, RTC and wake status. */
	MCHP_XEC_ESPI_PC_ACPI_PM1_REG_STS2,
	/** PM1 enable 1. Reserved by the ACPI specification, always zero. */
	MCHP_XEC_ESPI_PC_ACPI_PM1_REG_EN1,
	/** PM1 enable 2. Power button, sleep button and RTC enables. */
	MCHP_XEC_ESPI_PC_ACPI_PM1_REG_EN2,
	/** PM1 control 1. Reserved by the ACPI specification, always zero. */
	MCHP_XEC_ESPI_PC_ACPI_PM1_REG_CTRL1,
	/** PM1 control 2. Sleep type, sleep enable and power button override. */
	MCHP_XEC_ESPI_PC_ACPI_PM1_REG_CTRL2,
	/** PM1 control 2 byte 1. Reserved by the ACPI specification. */
	MCHP_XEC_ESPI_PC_ACPI_PM1_REG_CTRL21,
	/** PM1 control 2 byte 2. Reserved by the ACPI specification. */
	MCHP_XEC_ESPI_PC_ACPI_PM1_REG_CTRL22,
	/** EC power management status. Bit 0 is the SCI request. */
	MCHP_XEC_ESPI_PC_ACPI_PM1_REG_PM_STS,
	MCHP_XEC_ESPI_PC_ACPI_PM1_REG_MAX,
};

/** @brief Event data reported for an ACPI PM1 event
 *
 * Placed in @ref espi_event::evt_data when @ref espi_event::evt_details is
 * @ref MCHP_XEC_ESPI_PERIPHERAL_ACPI_PM1.
 */
struct mchp_xec_espi_pc_acpi_pm1_evt {
	/** enum mchp_xec_espi_pc_acpi_pm1_reg the Host wrote */
	uint32_t reg: 8;
	/** Value the register holds after the Host write */
	uint32_t data: 8;
	/** Reserved for future use */
	uint32_t reserved: 16;
};

/** @brief Read an EC-side ACPI PM1 register
 *
 * @param dev ACPI PM1 peripheral channel device
 * @param reg register to read
 * @param val destination for the register value
 *
 * @retval 0 success
 * @retval -EINVAL dev or val is NULL, or reg is out of range
 */
int mchp_xec_espi_pc_acpi_pm1_get(const struct device *dev,
				  enum mchp_xec_espi_pc_acpi_pm1_reg reg, uint8_t *val);

/** @brief Write an EC-side ACPI PM1 register
 *
 * Bits the ACPI specification reserves are read-only in hardware and ignore the
 * value written.
 *
 * @param dev ACPI PM1 peripheral channel device
 * @param reg register to write
 * @param val value to write
 *
 * @retval 0 success
 * @retval -EINVAL dev is NULL or reg is out of range
 */
int mchp_xec_espi_pc_acpi_pm1_set(const struct device *dev,
				  enum mchp_xec_espi_pc_acpi_pm1_reg reg, uint8_t val);

#endif /* CONFIG_ESPI_XEC_V3_PC_ACPI_PM1 */

#ifdef CONFIG_ESPI_XEC_V3_PC_EMI

/** @brief Vendor peripheral identifier reported in struct espi_event evt_details
 *         for an Embedded Memory Interface event.
 *
 * The generic enum espi_virtual_peripheral has no Embedded Memory Interface
 * entry, so this identifier is numbered above the highest generic value in the
 * same way MCHP_XEC_ESPI_PERIPHERAL_MAILBOX is.
 */
#define MCHP_XEC_ESPI_PERIPHERAL_EMI 0x102U

/** @brief The two SoC data memory regions one EMI instance windows to the Host
 *
 * Bit[15] of the address the Host writes to the EMI address register selects
 * which region the following data access reaches.
 */
enum mchp_xec_espi_pc_emi_region {
	MCHP_XEC_ESPI_PC_EMI_REGION_0 = 0,
	MCHP_XEC_ESPI_PC_EMI_REGION_1,
	MCHP_XEC_ESPI_PC_EMI_REGION_MAX,
};

/** @brief Payload of an EMI peripheral channel event
 *
 * Cast the evt_data member of struct espi_event to this type when evt_details
 * is MCHP_XEC_ESPI_PERIPHERAL_EMI.
 */
struct mchp_xec_espi_pc_emi_evt {
	uint32_t ldn: 8;  /**< logical device number of the reporting EMI */
	uint32_t data: 8; /**< value the Host wrote to the Host-to-EC mailbox */
	uint32_t reserved: 16;
};

/** @brief Point one EMI memory region at a buffer the caller owns
 *
 * Replaces the region the emi-mems device tree property describes, for a caller
 * that allocates the buffer itself. The driver keeps the values and re-applies
 * them whenever the eSPI controller reports the Host facing hardware has come
 * out of reset, so the region survives an eSPI Reset or PLTRST cycle.
 *
 * Hardware ignores the low two address bits and the low two bits of each limit,
 * so pass a four byte aligned buffer. A limit is the exclusive byte offset the
 * Host may reach: reads are allowed below @p rd_limit and writes below
 * @p wr_limit, which is how a region exposes a read-only tail.
 *
 * @param dev EMI peripheral channel device
 * @param region region to program
 * @param base start of the buffer, or NULL to disable the region
 * @param rd_limit byte offset the Host may read up to
 * @param wr_limit byte offset the Host may write up to
 *
 * @retval 0 success
 * @retval -EINVAL dev is NULL or region is out of range
 */
int mchp_xec_espi_pc_emi_region_set(const struct device *dev,
				    enum mchp_xec_espi_pc_emi_region region, void *base,
				    uint16_t rd_limit, uint16_t wr_limit);

/** @brief Read the two EMI mailbox registers
 *
 * @param dev EMI peripheral channel device
 * @param h2ec where to store the Host-to-EC mailbox, may be NULL
 * @param ec2h where to store the EC-to-Host mailbox, may be NULL
 *
 * @retval 0 success
 * @retval -EINVAL dev is NULL
 */
int mchp_xec_espi_pc_emi_mbox_get(const struct device *dev, uint8_t *h2ec, uint8_t *ec2h);

/** @brief Write the EC-to-Host EMI mailbox register
 *
 * @param dev EMI peripheral channel device
 * @param ec2h value the Host will read from the EC-to-Host mailbox
 *
 * @retval 0 success
 * @retval -EINVAL dev is NULL
 */
int mchp_xec_espi_pc_emi_mbox_set(const struct device *dev, uint8_t ec2h);

/** @brief Raise EC-to-Host EMI software interrupt sources
 *
 * Sets bits in the EMI interrupt source set register. Bit N of @p swi_bits
 * corresponds to software interrupt source N, which the Host sees in the EMI
 * interrupt source register and clears by writing it back. Bit 0 is owned by
 * hardware and reports an EC write to the EC-to-Host mailbox; it is ignored
 * here.
 *
 * @param dev EMI peripheral channel device
 * @param swi_bits bit mask of software interrupt sources to raise
 *
 * @retval 0 success
 * @retval -EINVAL dev is NULL
 */
int mchp_xec_espi_pc_emi_host_swi_set(const struct device *dev, uint16_t swi_bits);

#endif /* CONFIG_ESPI_XEC_V3_PC_EMI */

#ifdef CONFIG_ESPI_XEC_V3_PC_GLUE

/** @brief Vendor peripheral identifier reported in struct espi_event evt_details
 *         for a glue logic signal monitor event.
 *
 * The generic enum espi_virtual_peripheral has no power good generation entry,
 * so this follows the other vendor identifiers above the highest generic value.
 */
#define MCHP_XEC_ESPI_PERIPHERAL_GLUE 0x103U

/** Derived VCC_PWRGD2 power good signal presented to the Host chipset */
#define MCHP_XEC_ESPI_PC_GLUE_SIG_PWRGD 0x01U
/** Derived S0ix connected standby state */
#define MCHP_XEC_ESPI_PC_GLUE_SIG_S0IX 0x02U

/** @brief Event data reported for a glue logic signal monitor event
 *
 * Placed in struct espi_event evt_data when evt_details is
 * MCHP_XEC_ESPI_PERIPHERAL_GLUE. Hardware detects both edges, so a handler that
 * needs the direction of a change reads it from the state field rather than
 * inferring it.
 */
struct mchp_xec_espi_pc_glue_evt {
	/** Signal states after the change, as MCHP_XEC_ESPI_PC_GLUE_SIG_* bits */
	uint32_t state: 8;
	/** Signals that changed, as MCHP_XEC_ESPI_PC_GLUE_SIG_* bits */
	uint32_t edges: 8;
	/** Reserved for future use */
	uint32_t reserved: 16;
};

/** @brief Read the glue logic signal monitor state
 *
 * @param dev glue logic peripheral channel device
 * @param state destination for the MCHP_XEC_ESPI_PC_GLUE_SIG_* bits
 *
 * @retval 0 success
 * @retval -EINVAL dev or state is NULL
 */
int mchp_xec_espi_pc_glue_state_get(const struct device *dev, uint8_t *state);

/** @brief Enable or disable glue logic signal monitor interrupts
 *
 * Selects which signals raise an event when they change. Any signal not named
 * in @p sig_mask keeps its current setting. Pending edges on a signal being
 * enabled are dropped, so enabling reports the next change rather than one that
 * happened while the signal was masked.
 *
 * @param dev glue logic peripheral channel device
 * @param sig_mask MCHP_XEC_ESPI_PC_GLUE_SIG_* bits to act on
 * @param enable non-zero to enable, zero to disable
 *
 * @retval 0 success
 * @retval -EINVAL dev is NULL or sig_mask names no known signal
 */
int mchp_xec_espi_pc_glue_ictrl(const struct device *dev, uint8_t sig_mask, uint8_t enable);

/** @brief Enable or disable S0ix state detection
 *
 * While detection is disabled the S0ix state is a constant zero, so VCC_PWRGD2
 * follows the VCC_PWRGD pin whatever the pwrgd-source device tree property
 * says. Hardware clears the enable on every PLTRST; the driver re-applies the
 * last value asked for here once the eSPI controller reports the Host facing
 * hardware usable again, so a caller does not have to watch for the reset
 * itself.
 *
 * @param dev glue logic peripheral channel device
 * @param enable non-zero to enable detection, zero to disable it
 *
 * @retval 0 success
 * @retval -EINVAL dev is NULL
 */
int mchp_xec_espi_pc_glue_s0ix_detect_enable(const struct device *dev, uint8_t enable);

#endif /* CONFIG_ESPI_XEC_V3_PC_GLUE */

#endif /* INCLUDE_ZEPHYR_DRIVERS_ESPI_MCHP_XEC_ESPI_H_ */
