# Enable config log
CONFIG_STDOUT_CONSOLE=y
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y

CONFIG_FLASH=y
CONFIG_MSPI=y

# Do not use. Loads Zephyr DMA driver
# CONFIG_MSPI_DMA=y
# Instead use this
CONFIG_MSPI_MCHP_XEC_QMSPI_LDMA=y

CONFIG_PM=n
CONFIG_DEBUG=y
