# Enable config log
CONFIG_STDOUT_CONSOLE=y
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y

# CONFIG_FLASH=y
# CONFIG_FLASH_JESD216_API=y

CONFIG_MSPI=y
# Original MSPI Kconfig would load DMA driver
# QMSPI (except MEC15xx) has local-DMA channels
# We modified MSPI Kconfig to not enable DMA if
# our MSPI driver is enabled
CONFIG_MSPI_DMA=y

CONFIG_FLASH=y
CONFIG_FLASH_JESD216_API=y
CONFIG_FLASH_MSPI_NOR_USE_SFDP=y

# we only need pseudo-random for test patterns
CONFIG_TEST_RANDOM_GENERATOR=y

# If CONFIG_PM=n Zephyr PINCTRL macros remove pinctrl-1 used for sleep
# This causes the PINCTRL macros to fail for pinctrl-2 and onwards.
# Enable PINCTRL keep sleep state to preserve pinctrl-1 pointer slot.
# Moved to select rule in drivers/mspi/Kconfig.mchp_xec
# CONFIG_PINCTRL_KEEP_SLEEP_STATE=y

CONFIG_PM=n

# Usage fault in MSPI driver debug routine calling LOG_INF many time
# try increasing main stack size
CONFIG_MAIN_STACK_SIZE=2048

#CONFIG_DEBUG=y
