# Enable config log
CONFIG_STDOUT_CONSOLE=y
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y

CONFIG_FLASH=y
CONFIG_MSPI=y
# Enabling CONFIG_MSPI_DMA selects CONFIG_DMA
# We do not need the DMA driver because QMSPI has
# built-in DMA channels. Use CONFIG_MSPI_XEC_QSPI_LDMA=y 
# CONFIG_MSPI_DMA=y
CONFIG_MSPI_XEC_QSPI_LDMA=y

CONFIG_PM=n
CONFIG_DEBUG=y
