# Copyright (c) 2026 Microchip Technology Inc.
# SPDX-License-Identifier: Apache-2.0
#
# This file contains selected Kconfig options for the application.

CONFIG_STDOUT_CONSOLE=y
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y

CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

CONFIG_DMA=y
CONFIG_DMA_MCHP_XEC_MAX_BLOCKS_PER_CHAN=4

CONFIG_I2C=y
CONFIG_I2C_MCHP_XEC_NL_STATE_CAPTURE=y

# CONFIG_I2C_CALLBACK=y
# CONFIG_I2C_TARGET=y
# CONFIG_I2C_TARGET_BUFFER_MODE=y

# Turn on SoC only PM
# CONFIG_PM=y
