# Enable config log
CONFIG_STDOUT_CONSOLE=y
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y

CONFIG_DMA=y
CONFIG_MSPI=y
CONFIG_MSPI_DMA=y
CONFIG_MSPI_ASYNC=y

# Flash MSPI NOR driver init calls MSPI driver.
# Ensure our MSPI driver loads before Flash MSPI NOR.
CONFIG_MSPI_INIT_PRIORITY=49

CONFIG_FLASH=y
CONFIG_FLASH_JESD216_API=y
CONFIG_FLASH_MSPI_NOR_USE_SFDP=y

# we use pseudo-random data for test patterns
CONFIG_TEST_RANDOM_GENERATOR=y
