CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_GPIO=y
CONFIG_PINCTRL=y
CONFIG_PM=n

CONFIG_ESPI=y
CONFIG_ESPI_LOG_LEVEL_INF=y

# Host emulator waits for the Target to send TARGET_BOOT_DONE/STATUS
CONFIG_ESPI_AUTOMATIC_BOOT_DONE_ACKNOWLEDGE=n

# ACPI_EC0 (62h/66h), 8042 KBC and Port 80h
CONFIG_ESPI_PERIPHERAL_HOST_IO=y
CONFIG_ESPI_PERIPHERAL_8042_KBC=y
CONFIG_ESPI_PERIPHERAL_DEBUG_PORT_80=y

# Generic ACPI ECs used by the Host emulator I/O writes
CONFIG_ESPI_PERIPHERAL_HOST_IO_PVT=n
CONFIG_ESPI_PERIPHERAL_HOST_IO_PVT2=y
CONFIG_ESPI_PERIPHERAL_HOST_IO_PVT2_PORT_NUM=0x320
CONFIG_ESPI_PERIPHERAL_HOST_IO_PVT3=y
CONFIG_ESPI_PERIPHERAL_HOST_IO_PVT3_PORT_NUM=0x330
CONFIG_ESPI_PERIPHERAL_XEC_ACPI_EC4=y
CONFIG_ESPI_PERIPHERAL_XEC_ACPI_EC4_PORT_NUM=0x340

# EMI0/EMI1 mapped to Host memory
CONFIG_ESPI_PERIPHERAL_XEC_EMI=y

# Not used by the Host emulator
CONFIG_ESPI_PERIPHERAL_UART=n
CONFIG_ESPI_PERIPHERAL_XEC_MAILBOX=n
