# Enable config log
CONFIG_STDOUT_CONSOLE=y
CONFIG_LOG=y

CONFIG_I2C=y
CONFIG_I2C_MCHP_XEC_V3_INSTRUMENT_ISR=y
CONFIG_I2C_CALLBACK=y
CONFIG_I2C_TARGET=y
# CONFIG_I2C_TARGET_BUFFER_MODE=y
CONFIG_I2C_EEPROM_TARGET=y
CONFIG_I2C_VIRTUAL=y

CONFIG_PM=n
CONFIG_DEBUG=y

